name: CI
on: [push, pull_request]

jobs:

  unit-test:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install utest --quiet
          haxelib install hxp --quiet

      - name: Setup environment
        run: |
          haxelib dev openfl $GITHUB_WORKSPACE

      - name: Install "openfl" command alias
        run: |
          haxelib run openfl setup -alias -y

      - name: Run tests
        run: |
          haxelib run hxp --install-hxp-alias
          hxp test

  package-haxelib:
    runs-on: macos-10.15
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install hxp --quiet

      - name: Rebuild OpenFL run.n
        working-directory: scripts
        run: |
          haxe run.hxml

      - uses: actions/upload-artifact@v2
        with:
          name: openfl-haxelib
          path: |
            ./
            !tests/
            !haxe-*-*/
            !neko-*-*/
            !.git/
          if-no-files-found: error

  docs:
    runs-on: macos-10.15
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime --quiet
          haxelib install dox --quiet
          haxelib dev openfl $GITHUB_WORKSPACE

      - name: Build docs
        working-directory: scripts
        run: |
          haxe docs.hxml

      - uses: actions/upload-artifact@v2
        with:
          name: openfl-docs
          path: docs
          if-no-files-found: error

  notify:
    runs-on: ubuntu-16.04
    needs: [package-haxelib, docs, unit-test]
    if: always()
    steps:
      - name: Notify Discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          include-details: 'false'
